import type { VenueCategory } from "@/lib/venues/types"

export const DEADLINE_COLOR = "#dc2626"

export const categoryColors: Record<VenueCategory, string> = {
  HCI: "#eab308",
  "UI/UX": "#3b82f6",
  "VR/AR/XR": "#1e3a8a",
  "Mobile & Ubiquitous": "#06b6d4",
  "CSCW & Social": "#0891b2",
  "Games & Play": "#f97316",
  Design: "#22c55e",
  "Security & Privacy": "#92400e",
  "AI & Ethics": "#2563eb",
  "Sustainability & ICTD": "#65a30d",
  "Web & Social Media": "#7c3aed",
  Communication: "#a855f7",
  Systems: "#64748b",
  Children: "#ec4899",
  Graphics: "#b45309",
  "IT & Service Management": "#475569",
  "SNA & Communities": "#6d28d9",
  "Diffusion & Virality": "#7c3aed",
  "Sentiment & Opinions": "#8b5cf6",
  "Misinformation & Trust": "#a78bfa",
  "Web Mining & IR": "#5b21b6",
  "Digital Humanities": "#9333ea",
  "Politics & Civics": "#c026d3",
  "Digital Health": "#db2777",
  "Text & Demographics": "#e879f9",
  "Trends & Forecasting": "#d946ef",
  "Media Studies": "#a855f7",
  "Platform Studies": "#7e22ce",
  "Web Linguistics": "#6366f1",
  "Social Psychology": "#4f46e5",
  "Engagement & Gamification": "#f97316",
  "Social Innovation": "#14b8a6",
  "Organizational Social": "#0891b2",
  "Methods & Tools": "#0d9488",
  "Critical & Ethnographic": "#0f766e",
  "Domain Applications": "#14b8a6",
  "Ethics & Policy": "#2dd4bf",
  "Emerging Technologies": "#5eead4",
  "Crossing Boundaries": "#99f6e4",
  "Explainable AI & Trust": "#1d4ed8",
  "Conversational UX": "#2563eb",
  "AI UX Personalization": "#3b82f6",
  "AI-Augmented Design": "#60a5fa",
  "Human-AI Collaboration": "#93c5fd",
  "Generative UI": "#1e40af",
  "NLP in UX": "#3730a3",
  "Accessible & Inclusive Design": "#ca8a04",
  "Human-Robot Interaction": "#64748b",
  "Cross-Cultural UX": "#b45309",
  "Learning UX": "#ec4899",
  "Affective Computing": "#f472b6",
  "Persuasive Technology": "#fb923c",
  "Multimodal Interfaces": "#1e3a8a",
  "Computational Interaction": "#facc15",
  "Novel Devices & Fabrication": "#fde047",
}

export function colorForCategories(categories: VenueCategory[]): string {
  return categoryColors[categories[0] ?? "HCI"] ?? categoryColors.HCI
}

export const legendItems: { label: string; color: string }[] = [
  { label: "Deadlines", color: DEADLINE_COLOR },
  ...Object.entries(categoryColors).map(([label, color]) => ({ label, color })),
  { label: "Today", color: "var(--muted-foreground)" },
]
